### ISSUE TITLE
Winter Break To Dos 

### ISSUE THREAD

**Issue by cgreim** [CornerFarmChicago/farm-site#62]
- Find links to docs for resources page (Szymon, Cat)
- Build compost table into code (Szymon) 
- Finish content on volunteers page (Cat) 
- Edit content on About pages (Cat)

**Comment by sambors** [comment]
Compost page is built! We'll review and merge on Tuesday.

(Happy New Year to you all!)

**Comment by cgreim** [comment]
Content on volunteers page is drafted, and we started collecting resources in [this google doc](https://docs.google.com/document/d/12Ij4wlULUfKJjqUmWLP_7Fp_oRbot3MjcLfPfswPZCw/edit) and will ask the team to contribute.

The only item here we didn't get to was editing content on About pages; we can use https://github.com/cgreim/farm-site/issues/25 to track that and close this issue.
