### ISSUE TITLE
Add site navigation

### ISSUE THREAD

**Issue by cgreim** [CornerFarmChicago/farm-site#8]
Use site map in #1 , build with boostrap

**Comment by sambors** [comment]
Tried to get a Jekyll navigation bar working, which populates a navbar based on a navigation.yml file with general names and links. Didn't get it to work, but the file I created can be found at https://github.com/cgreim/farm-site/blob/navigation-yml/_data/navigation.yml

Referenced these tutorials:

- https://mycyberuniverse.com/web/jekyll-bootstrap-dynamic-navigation-highlighting-active-element.html
- https://learn.cloudcannon.com/jekyll/advanced-navigation/

**Comment by cgreim** [comment]
closed by (I think) #22
